

server:
  port: 8292

  ssl:
    enabled: true
    key-store: keystore.jks
    key-store-password: 123456
    key-store-type: JKS
    key-alias: tomcatssl
    #key-store: .keystore
    #key-store-type: JKS
    #key-store-provider: SUN
    #key-alias: tomcat
    #key-store-password: 123456
    #key-password: 654321
